import localFont from "next/font/local";
import Navbar from "../components/Navbar";
import { AuthProvider } from "./providers";
import "./globals.css";

export const metadata = {
  title: "Eisenhower ToDo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <AuthProvider>
      <Navbar/>
      <div className="flex-1">
              {children}
            </div>
        </AuthProvider>
      </body>
    </html>
  );
}
